## Numerical Python(Numpy) - Part 1

In [ ]:
# de facto standard (사실상의 표준)

In [5]:
import numpy as np

In [2]:
a = [1, 2, 3]
a * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [3]:
list(map(lambda x: 3*x, a))

[3, 6, 9]

In [6]:
b = np.array([1,2,3])
b * 3

array([3, 6, 9])

### 1.Numpy Dimension array

In [9]:
a = np.array([1, 4, 5, 8], float)
a

array([1., 4., 5., 8.])

In [8]:
type(a)

numpy.ndarray

In [10]:
a.dtype, a.shape

(dtype('float64'), (4,))

### 2, Array shape

In [13]:
# Vector 1d
vector = np.array([1, 4, 5, 8])
vector.shape

(4,)

In [14]:
# Matrix 2d
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
print(matrix.shape)
matrix

(2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
# Tensor 3d ↑
tensor = np.array([[[1, 2, 3],
                    [4, 5, 6]],
                   [[7, 8, 9],
                    [10, 11, 12]],
                   [[13, 14, 15],
                    [16, 17, 18]]
                   ])
tensor.shape

(3, 2, 3)

In [18]:
tensor = np.arange(1,25).reshape(2,3,4)
print(tensor)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [19]:
vector.shape, matrix.shape, tensor.shape

((4,), (2, 3), (2, 3, 4))

In [21]:
vector.size, matrix.size, tensor.size

(4, 6, 24)

In [22]:
# data type
# float32 : 32bit로 표시 - single precision
# float62 : 62bit로 표시 - double precision
a = np.array([1,2,3], dtype=np.float32)
a

array([1., 2., 3.], dtype=float32)

In [23]:
b = np.array([1,2,3], dtype=np.int16)
b

array([1, 2, 3], dtype=int16)

### reshape

In [24]:
# reshape / element의 갯수는 맞춰주고, 차원을 바꿔줌
matrix.shape

(2, 3)

In [25]:
matrix.reshape(6,)

array([1, 2, 3, 4, 5, 6])

In [26]:
matrix.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [27]:
# -1은 numpy가 알아서 맞춰줌 (단 size가 동일할때)
matrix.reshape(-1,)

array([1, 2, 3, 4, 5, 6])

In [28]:
matrix.reshape(3, -1)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [29]:
tensor.reshape(4, -1) # 4, -1 -> 4, 6

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [31]:
matrix.reshape(-1,)

array([1, 2, 3, 4, 5, 6])

In [32]:
matrix.reshape(1, -1)

array([[1, 2, 3, 4, 5, 6]])

In [33]:
matrix.reshape(-1, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

### flatten

In [41]:
tensor.reshape(-1,)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [36]:
tensor.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

### Indexing & Slicing

#### indexing

In [37]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
matrix[0][1]

2

In [40]:
matrix[0,1]

2

In [42]:
tensor[1,1,2]

19

#### slicing

In [43]:
b = np.arange(16).reshape(4, -1)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [44]:
# 5, 6, 9, 10
b[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [47]:
# 5, 6, 7, 9, 10 ,11
b[1:3, 1:4]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [49]:
# 1, 3, 9, 11
b[::2, 1::2]

array([[ 1,  3],
       [ 9, 11]])

In [62]:
# 2d ↑ 대문자 사용
# X는 앞에 3열 y 는 마지막 열
X, y = b[:, :-1], b[:, 3:4]
print(X, y)

X, y = b[:, :-1], b[:, -1]
print(X, y)

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]] [[ 3]
 [ 7]
 [11]
 [15]]
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]] [ 3  7 11 15]
