In [1]:
import numpy as np

In [4]:
# 연습문제 1.

a = np.arange(10, 90, 10).reshape(2,-1)
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [15]:
# 연습문제 2.

m = np.arange(0, 15).reshape(3,-1)

print('1) m[1,2] : ', m[1,2])
print('2) m[2,4] : ', m[2,4])
print('3) m[1,1:3] : ', m[1,1:3])
print('4) m[1:3,2] : ', m[1:3,2])
print('5) m[0:2,3:] : \n', m[0:2,3:])

1) m[1,2] :  7
2) m[2,4] :  14
3) m[1,1:3] :  [6 7]
4) m[1:3,2] :  [ 7 12]
5) m[0:2,3:] : 
 [[3 4]
 [8 9]]


In [35]:
# 연습문제 3.

f = m.reshape(-1)
print(f)

print(f'1) f[f%3 == 0] : {f[f%3 == 0]}')
print(f'2) f[f%4 == 1] : {f[f%4 == 1]}')
print(f'3) np.logical_and(f%3 == 0, f%4 ==1]) : {f[np.logical_and(f%3 == 0, f%4 ==1)]}') # ??

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
1) f[f%3 == 0] : [ 0  3  6  9 12]
2) f[f%4 == 1] : [ 1  5  9 13]
3) np.logical_and(f%3 == 0, f%4 ==1]) : [9]


In [32]:
# 연습문제 4.

a = np.eye(5, k=1)
b = np.eye(5) * 2
c = np.eye(5, k=-1) * 3
d = a + b + c
d

array([[2., 1., 0., 0., 0.],
       [3., 2., 1., 0., 0.],
       [0., 3., 2., 1., 0.],
       [0., 0., 3., 2., 1.],
       [0., 0., 0., 3., 2.]])

In [39]:
# 연습문제 5.

np.random.seed(2021)
m = np.random.uniform(0, 10, 30).reshape(5,6).round(4)

print(f'1) np.max(m) : {np.max(m)}')
print(f'2) np.sum(m, axis=1 : {np.sum(m, axis=1)}')
print(f'3) np.max(m, axis=1) : {np.max(m, axis=1)}')
print(f'4) np.mean(m, axis=0)) : {np.mean(m, axis=0)}')
print(f'5) np.min(m, axis=0) : {np.min(m, axis=0)}')

1) np.max(m) : 9.9724
2) np.sum(m, axis=1 : [29.1637 25.3385 38.0722 23.6387 32.0221]
3) np.max(m, axis=1) : [9.9724 7.8431 9.6384 5.743  8.231 ]
4) np.mean(m, axis=0)) : [5.81074 5.90066 3.7154  5.3664  6.02438 2.82946]
5) np.min(m, axis=0) : [1.7899 3.7116 0.8663 2.0185 0.9689 0.5857]


In [45]:
score = np.array([[1,2,3,4],[46,99,100,71],[81,59,90,100]])
score
score[:, np.argsort(score[1])[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

In [46]:
# 연습문제 7.
np.random.seed(2021)
dice = np.random.randint(1,7,100)
dice

array([5, 6, 2, 1, 6, 5, 4, 6, 6, 6, 1, 5, 2, 6, 2, 2, 5, 6, 3, 3, 1, 4,
       2, 1, 3, 4, 5, 6, 1, 6, 2, 3, 6, 2, 6, 2, 3, 3, 5, 6, 3, 4, 2, 3,
       3, 1, 3, 5, 6, 4, 4, 2, 2, 2, 3, 6, 4, 4, 5, 4, 2, 5, 2, 2, 5, 4,
       6, 4, 4, 4, 3, 2, 4, 3, 6, 3, 3, 1, 5, 4, 2, 4, 2, 5, 3, 4, 2, 3,
       6, 3, 6, 3, 4, 5, 6, 2, 2, 6, 1, 6])

In [47]:
np.mean(dice)

3.7